version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - db
    restart: always
    env_file:
      - .env

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"       # จะใช้จาก host ได้ทาง 5433 (ภายใน container คือ 5432)
    volumes:
      - pg_data:/var/lib/postgresql/data

  # (ทางเลือก) pgAdmin UI
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: always
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin123
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - db

volumes:
  pg_data:
